name: Build geosite.dat
on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * 5"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x.y
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - name: Compare latest tags and set variables
        run: |
          set -x
          upstreamLatestTag=$(curl -sSL --connect-timeout 5 -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/v2fly/domain-list-community/releases/latest | grep "tag_name" | cut -d\" -f4)
          thisLatestTag=$(curl -sSL --connect-timeout 5 -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/latest | grep "tag_name" | cut -d\" -f4)
          if [[ "X"$upstreamLatestTag != "X"$thisLatestTag ]]; then
            echo "NeedToSync=true" >> $GITHUB_ENV
          fi
          echo "RELEASE_NAME=$upstreamLatestTag" >> $GITHUB_ENV
          echo "TAG_NAME=$upstreamLatestTag" >> $GITHUB_ENV
          echo "GOOGLE_DOMAINS_URL=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf" >> $GITHUB_ENV
          echo "APPLE_DOMAINS_URL=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf" >> $GITHUB_ENV
          
        shell: bash

      - name: Checkout codebase
        uses: actions/checkout@v3
        if: ${{ env.NeedToSync }}

      - name: Checkout v2fly/domain-list-community
        if: ${{ env.NeedToSync }}
        uses: actions/checkout@v3
        with:
          repository: v2fly/domain-list-community
          path: domain-list-community

      - name: Append attribute rules
        if: ${{ env.NeedToSync }}
        run: |
          echo "include:geolocation-!cn @cn" >> ./domain-list-community/data/cn
          echo "include:geolocation-cn @!cn" >> ./domain-list-community/data/geolocation-\!cn
          sed -i '/alicdn/d' ./domain-list-community/data/alibaba-ads
          sed -i '/tiktok/d' ./domain-list-community/data/bytedance
          sed -i '/supercell.com/d' ./domain-list-community/data/tencent-games

          curl -sSL $GOOGLE_DOMAINS_URL | perl -ne '/^server=\/([^\/]+)\// && print "full:$1\n"' > ./domain-list-community/data/google-cn
          curl -sSL $APPLE_DOMAINS_URL | perl -ne '/^server=\/([^\/]+)\// && print "full:$1\n"' > ./domain-list-community/data/apple-cn
          
      - name: Get dependencies and run
        if: ${{ env.NeedToSync }}
        run: |
          go run ./ --datapath=./domain-list-community/data

      - name: Generate sha256 hashsum
        if: ${{ env.NeedToSync }}
        run: |
          cd publish || exit 1
          sha256sum geosite.dat > geosite.dat.sha256sum

      - name: Git push assets to "release" branch
        if: ${{ env.NeedToSync }}
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add publish "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f publish release

      - name: Create a release
        if: ${{ env.NeedToSync }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

      - name: Upload geosite.dat
        if: ${{ env.NeedToSync }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/geosite.dat
          asset_name: geosite.dat
          asset_content_type: application/octet-stream

      - name: Upload geosite.dat sha256sum
        if: ${{ env.NeedToSync }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/geosite.dat.sha256sum
          asset_name: geosite.dat.sha256sum
          asset_content_type: text/plain
